#!/bin/bash -lv

case "$DISTRO_NAME" in
    centos* | rhel*)
	KERNEL_VERSION=$(ls /boot/vmlinuz*x86_64 | sort -n | tail -n1 | cut -d'-' -f2-)
	yum install -y kernel-devel-$KERNEL_VERSION kernel-headers-$KERNEL_VERSION
	yum install -y $NVIDIA_CUDA_PKGLIST
	;;
    fedora*)
	KERNEL_VERSION=$(ls /boot/vmlinuz*x86_64 | sort -n | tail -n1 | cut -d'-' -f2-)
	dnf install -y kernel-devel-$KERNEL_VERSION kernel-headers-$KERNEL_VERSION
	dnf install -y $NVIDIA_CUDA_PKGLIST
	;;
    ubuntu* | debian*)
	KERNEL_VERSION="$(ls /boot/vmlinuz*generic | sort -n | tail -n1 | cut -d'-' -f2-)"
	apt-get -y install linux-headers-$KERNEL_VERSION
	apt-get -y install $NVIDIA_CUDA_PKGLIST
	;;
    *)
	echo "Distro \"$DISTRO_NAME\" is not recognised"
	exit -1
	;;
esac

exit 0
