#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p /etc/systemd/system/slurmd.service.d/

cat <<EOF > /etc/systemd/system/slurmd.service.d/slurmconf.conf
[Unit]
RequiresMountsFor="$SLURMD_NETWORK_MOUNT"
ConditionPathExists="$SLURMD_NETWORK_CONF_PATH"
EOF

cat <<EOF > /etc/sysconfig/slurmd
SLURMD_OPTIONS="-f $SLURMD_NETWORK_CONF_PATH"
EOF