#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

for value in $(compgen -v); do
    if [[ "$value" =~ DIB_ANSIBLE_(.*)_SRC ]]; then
        name="${BASH_REMATCH[1]}"
        repo_ref="DIB_ANSIBLE_""$name""_SRC"
        repo=${!repo_ref:?"You must set DIB_ANSIBLE_$name""_SRC"}
        opts_ref="DIB_ANSIBLE_""$name""_OPTS"
        opts="${!opts_ref:-}"
        # Use vault password helper to avoid writing password to disk
        vault_ref="DIB_ANSIBLE_""$name""_VAULT_PASSWORD"
        export ANSIBLE_VAULT_PASSWORD="${!vault_ref:-}"
        vault_password=""
        if [ ! -z ${ANSIBLE_VAULT_PASSWORD:+x} ]; then
            vault_password="--vault-password-file /opt/ansible-pull/bin/vault-password-helper.sh"
        fi
        "$DIB_ANSIBLE_VENV/bin/ansible-pull" $vault_password -U "$repo" $opts
   fi
done
