#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

KEEP=""
# Purge the cloud image default network configuration
for INF in ${DHCP_ON_DEV}; do
	if [ "$INF" == "eth0" ];then
		KEEP="1"
	fi
done
if [ "$KEEP" != "1" ]
then
    [ -f /etc/sysconfig/network-scripts/ifcfg-eth0 ] && rm -f /etc/sysconfig/network-scripts/ifcfg-eth0
    [ -f /etc/network/interfaces.d/eth0.cfg ] && rm -f /etc/network/interfaces.d/eth0.cfg
fi
