#!/bin/bash -l

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -euo pipefail

if [[ ${DISTRO_NAME} =~ (centos|rhel|rocky) && -n ${DIB_ELREPO_PKGLIST} ]]; then
    dnf install -y "${DIB_ELREPO_PKGLIST}"
else
    echo "You must set the package list: \"$DIB_ELREPO_PKGLIST\"."
    exit 1
fi

exit 0
