#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -d /etc/yum.repos.d ] || exit -1
${OPENHPC_PKGMGR} install -y ${OPENHPC_REPO_RPM}

if [ "$DIB_OPENHPC_VERSION" = "2.0" ]
then
    ${OPENHPC_PKGMGR} config-manager --set-enabled powertools
fi
