#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

export YUM=dnf

if $(which dnf); then
    dnf install -y $DIB_PYTHON_VERSION && \
    ln -sf /bin/$DIB_PYTHON_VERSION /bin/python3 && \
    ln -sf /usr/bin/$DIB_PYTHON_VERSION /usr/bin/python3 && \
    python3 -m ensurepip
else
    echo "DNF not found: Selected python was not installed"
fi
