#!/usr/bin/env bash

# /etc/machine-id needs to be populated for /bin/kernel-install to
# correctly copy kernels into /boot.  We will clear this out in the
# final image.
systemd-machine-id-setup --print
