#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e
set -o pipefail

if [ "$OPENHPC_DELETE_REPO" = "y" -o "$OPENHPC_DELETE_REPO" = "Y" ]
then
    rm -f /etc/yum.repos.d/OpenHPC.repo
fi

systemctl enable ntpd.service
