#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

sudo curl \
    -o /etc/yum.repos.d/docker-ce.repo \
    ${DIB_DOCKER_REPO_URL}

for repo in ${DIB_DOCKER_ENABLED_REPOS}; do
    sudo awk \
    'f==1 && /enabled=0/ {$0="enabled=1"; f=0} /\['${repo}'\]/ {f=1}enabled=1' \
    /etc/yum.repos.d/docker-ce.repo > /etc/yum.repos.d/docker-ce.repo.bak
    sudo mv /etc/yum.repos.d/docker-ce.repo.bak /etc/yum.repos.d/docker-ce.repo
done
