#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "${DIB_SUDOERS_CONFIG}" > /etc/sudoers.d/${DIB_SUDOERS_FILENAME}
chmod 0440 /etc/sudoers.d/${DIB_SUDOERS_FILENAME}
visudo -c || (rm /etc/sudoers.d/${DIB_SUDOERS_FILENAME} && false)
