#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /etc/yum.repos.d ] ; then
cat > /etc/yum.repos.d/MLNX-OFED.repo << EOF
[MLNX-OFED-$MLNX_OFED_VERSION]
name=MLNX-OFED-$MLNX_OFED_VERSION
type=rpm-md
baseurl=$MLNX_OFED_REPO/RPMS
gpgcheck=1
gpgkey=$MLNX_OFED_REPO/RPM-GPG-KEY-Mellanox
enabled=1
EOF
fi

if [ -d /etc/apt/sources.list.d ] ; then
cat > /etc/apt/sources.list.d/mlnx_ofed.list << EOF
deb $MLNX_OFED_REPO/DEBS ./
EOF
wget -qO - $MLNX_OFED_REPO/RPM-GPG-KEY-Mellanox | sudo apt-key add -
fi

