#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -d /etc/yum.repos.d ] ; then
cat > /etc/yum.repos.d/MLNX-OFED.repo << EOF
[MLNX-OFED-$MLNX_OFED_VERSION]
name=MLNX-OFED-$MLNX_OFED_VERSION
type=rpm-md
baseurl=$MLNX_OFED_REPO/RPMS
gpgcheck=1
gpgkey=$MLNX_OFED_REPO/RPM-GPG-KEY-Mellanox
enabled=1
EOF
fi

if [ -d /etc/apt/sources.list.d ] ; then
cat > /etc/apt/sources.list.d/mlnx_ofed.list << EOF
deb [signed-by=/etc/apt/keyrings/RPM-GPG-KEY-Mellanox.gpg] $MLNX_OFED_REPO ./
EOF
sudo mkdir -p /etc/apt/keyrings/
wget -qO - https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | gpg --dearmor -o /etc/apt/keyrings/RPM-GPG-KEY-Mellanox.gpg
# wget $MLNX_OFED_REPO -O /tmp/MLNX-OFED-$MLNX_OFED_VERSION.tgz
# mkdir /tmp/MLNX-OFED-$MLNX_OFED_VERSION
# tar -vxzf /tmp/MLNX-OFED-$MLNX_OFED_VERSION.tgz -C /tmp/MLNX-OFED-$MLNX_OFED_VERSION
# chmod +x /tmp/MLNX-OFED-$MLNX_OFED_VERSION/MLNX_OFED_SRC-$MLNX_OFED_VERSION/install.pl

fi

