#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if $(which dnf > /dev/null 2>&1); then
    dnf config-manager --add-repo "$MLNX_OFED_REPO_FILE"
elif $(which yum-config-manager > /dev/null 2>&1); then
    yum-config-manager --add-repo "$MLNX_OFED_REPO_FILE"
else
   echo "Unsupported distro"
   exit -1
fi

rpm --import http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
