#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if $(which dnf > /dev/null 2>&1); then
    dnf group install -y "Infiniband Support"
elif $(which dnf > /dev/null 2>&1); then
    yum groupinstall -y "Infiniband Support"
else
   echo "Unsupported distro"
   exit -1
fi
