#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

IPADIR=/usr/share/ironic-python-agent
PACKAGE=${DIB_IPA_HARDWARE_PACKAGE:-hardware${DIB_IPA_HARDWARE_VERSION:+==}${DIB_IPA_HARDWARE_VERSION:-}}

# Install the python hardware package inside the virtual environment.
$IPADIR/venv/bin/pip install -c $IPADIR/upper-constraints.txt $PACKAGE

# Because the ironic-python-agent systemd unit does not activate the virtualenv
# before executing the ironic-python-agent script, the PATH is not updated to
# point to the bin directory in the virtual environment. We add this symlink so
# that ironic-python-agent sees the hardware-detect tool in its PATH.
ln -s $IPADIR/venv/bin/hardware-detect /usr/local/bin/hardware-detect

# Install additional packages as requested.
if [[ -n ${DIB_IPA_EXTRA_HARDWARE_PACKAGES:-} ]]; then
    install-packages ${DIB_IPA_EXTRA_HARDWARE_PACKAGES}
fi
