#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -d /etc/yum.repos.d ] || exit -1

cat > /etc/yum.repos.d/ALaSKA-Extras.repo << EOF
[ALaSKA-Extras]
name=ALaSKA-Extras
type=rpm-md
baseurl=$ALASKA_REPO
gpgcheck=0
enabled=1
EOF
