#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

workspace=$(dirname $0)

[ -d /etc/yum.repos.d ] || exit -1
cp -n $workspace/ALaSKA-Extras.repo /etc/yum.repos.d/
