#!/bin/bash -l

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -euo pipefail

case "$DISTRO_NAME" in
    centos* )

	dnf -y install centos-release-kmods

	if [ ${DIB_CENTOS_KMODS_TESTING:-0} -eq 1 ]; then
		dnf config-manager --set-disabled centos-kmods
		dnf config-manager --set-enabled centos-kmods-testing
		dnf config-manager --set-enabled centos-kmods-rebuild-testing
	else
		dnf config-manager --set-enabled centos-kmods-rebuild
	fi

	;;
    *)
	echo "Distro \"$DISTRO_NAME\" is not supported"
	exit 1
	;;
esac

exit 0
