#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ ! -z "$OPENHPC_GRPLIST" ] && yum groupinstall -y $OPENHPC_GRPLIST
[ ! -z "$OPENHPC_PKGLIST" ] && yum install -y $OPENHPC_PKGLIST
