#!/bin/bash

OPENHPC_GRPLIST=${DIB_OPENHPC_GRPLIST:-"ohpc-base-compute ohpc-slurm-client 'InfiniBand Support'"}
OPENHPC_PKGLIST=${DIB_OPENHPC_PKGLIST:-"lmod-ohpc mrsh-ohpc lustre-client-ohpc"}
OPENHPC_DELETE_REPO=${DIB_OPENHPC_DELETE_REPO:-n}
