#!/bin/bash

export ANACONDA_PYTHON_VER=${DIB_ANACONDA_PYTHON_VER:-"2"}
export ANACONDA_RELEASE=${DIB_ANACONDA_RELEASE:-"4.4.0"}
export ANACONDA_INSTALLER_URL="https://repo.continuum.io/archive/Anaconda${ANACONDA_PYTHON_VER}-${ANACONDA_RELEASE}-Linux-x86_64.sh"
export ANACONDA_INSTALLER_LOCAL="/tmp/anaconda-installer.sh"
export ANACONDA_ROOT="/opt/anaconda"
