#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

if $(which yum > /dev/null 2>&1); then
    yum install -y $DIB_RPMS
elif $(which zypper > /dev/null 2>&1); then
    pushd /tmp
    for pkg in DIB_RPMS; do
        curl -O "$pkg"
        zypper -n in $(basename "$pkg")
    done
    popd
fi
