#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e
set -o pipefail

if [ "$MLNX_OFED_DELETE_REPO" = "y" -o "$MLNX_OFED_DELETE_REPO" = "Y" ]
then
    rm -f /etc/yum.repos.d/MLNX-OFED.repo
fi

if systemctl is-active sharpd; then
   systemctl stop sharpd
fi
