#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

sudo rm -f $TARGET_ROOT/etc/systemd/system/tmp.mount && echo "Successfully removed etc/systemd/system/tmp.mount" || true
