#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

printf "$NM_DISPATCHER_CONTENT" >> /etc/NetworkManager/dispatcher.d/$NM_DISPATCHER_FILENAME
chmod +x /etc/NetworkManager/dispatcher.d/$NM_DISPATCHER_FILENAME
