#!/bin/bash

export SLURMD_NETWORK_MOUNT=${DIB_SLURMD_NETWORK_MOUNT:?"You must set the environment variable: DIB_SLURMD_NETWORK_MOUNT"}
export SLURMD_NETWORK_CONF_PATH=${DIB_SLURMD_NETWORK_CONF_PATH:?"You must set the environment variable: DIB_SLURMD_NETWORK_CONF_PATH"}
